### ISSUE TITLE
Seems like onClick don't work

### ISSUE THREAD

**Issue by naivekook** [2dxgujun/Kpan#4]
Hello, 
I downloaded sample app and Clickable span don't work for me.

**Comment by 2dxgujun** [comment]
Aha, it's a stupid bug. I have released v1.7, and it should be fixed, also I remove the default link text color and the underline decoration for clickable span, let you decorate text on your need.
![image](https://user-images.githubusercontent.com/8072733/39027890-a3eae8f6-4486-11e8-8560-b5ac02d39de3.png)
